[project]
name = "data-parallel-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.3"
dependencies = [
    "torch==2.9.0",
    "transformers==4.57.3",
    "vllm==0.13.0",
    "triton==3.5.0",
    "kernels==0.11.7",
    "flash-attn==2.8.3",
    "jaxtyping==0.3.5",
    "more-itertools==10.7.0",
    "peft==0.18.1",
    "wandb==0.23.1",
    "datasets==3.6.0",
    "flashinfer-python==0.5.3", # this line is important because installing flashinfer speeds up vllm significantly
]

[tool.uv.sources]
flash-attn = { url = "https://github.com/mjun0812/flash-attention-prebuild-wheels/releases/download/v0.7.0/flash_attn-2.8.3+cu128torch2.9-cp312-cp312-linux_x86_64.whl" }
